// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YoAyudoPR.Web.Domain.Entities
{
    public partial class Activitylog
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int EventId { get; set; }
        public int? Hoursvolunteered { get; set; }
        public DateTime? Createdat { get; set; }
        public DateTime? Updatedat { get; set; }
        public string Status { get; set; }
        public Guid? Guid { get; set; }

        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}