// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace YoAyudoPR.Web.Domain.Entities
{
    public partial class Event
    {
        public Event()
        {
            Activitylogs = new HashSet<Activitylog>();
        }

        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public string Description { get; set; }
        public DateTime? Startdate { get; set; }
        public DateTime? Enddate { get; set; }
        public int? Capacity { get; set; }
        public DateTime? Createdat { get; set; }
        public string Websiteurl { get; set; }
        public string Address { get; set; }
        public int CategoryId { get; set; }
        public Guid? Guid { get; set; }
        public string Name { get; set; }
        public bool Isdeleted { get; set; }
        public bool? Isactive { get; set; }

        public virtual Category Category { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Activitylog> Activitylogs { get; set; }
    }
}